import type { Metadata } from 'next';
import Link from 'next/link';
import {
  ChevronRight,
  Home,
  Star,
  MapPin,
  Clock,
  DollarSign,
  CheckCircle,
  AlertTriangle,
  Car,
  Camera,
  Compass,
  Heart,
  Eye,
  Sparkles,
  Mountain,
  Info,
  Lightbulb,
  Users,
  Globe,
  BookOpen,
  Leaf,
  Shield,
  Sun,
  Moon,
  Sunrise,
  Sunset,
  Calendar,
  ArrowRight,
  Utensils,
  Bed,
  ShoppingBag,
  Landmark,
  Building,
  TreePine,
  Navigation,
  Wine,
  Music,
  Palette,
  Coffee,
  Footprints,
  Ticket,
  HandCoins,
  ThermometerSun,
  CloudSun,
  Umbrella,
  BadgeCheck,
  CircleDot,
  Map,
  Phone,
  MessageSquare,
  Ship,
  Anchor,
  Train,
  Pen,
  Film,
  Waves,
  BusFront,
  HelpCircle,
} from 'lucide-react';

/* =====================================================================
   SEO METADATA
   ===================================================================== */

export const metadata: Metadata = {
  title: 'Tangier Travel Guide 2025-2026 | Where Africa Meets Europe | Gateway Between Continents',
  description:
    'The ultimate Tangier travel guide. Explore the Kasbah, Cap Spartel, Caves of Hercules, Petit Socco, the American Legation Museum, and the Beat Generation literary trail. Best restaurants, ferries to Spain, TGV train, day trips to Chefchaouen and Asilah, nightlife, budget tips, and safety advice.',
  keywords: [
    'Tangier travel guide',
    'Tangier Morocco',
    'Tangier medina',
    'Cap Spartel',
    'Caves of Hercules',
    'Tangier ferry Spain',
    'Tangier Kasbah',
    'Petit Socco Tangier',
    'Grand Socco Tangier',
    'American Legation Museum',
    'Paul Bowles Tangier',
    'Beat Generation Morocco',
    'Cafe Hafa Tangier',
    'Tangier restaurants',
    'Tangier nightlife',
    'TangerMed port',
    'Al Boraq TGV Morocco',
    'Tangier to Casablanca train',
    'Tangier to Tarifa ferry',
    'Tangier day trips',
    'Asilah day trip',
    'Chefchaouen from Tangier',
    'Tangier hotels',
    'El Minzah Hotel',
    'Tangier safety tips',
    'Tangier budget guide',
    'best time to visit Tangier',
    'Tangier literary history',
    'William Burroughs Tangier',
    'Tangier International Zone',
  ],
  openGraph: {
    title: 'Tangier Travel Guide 2025-2026 | Where Africa Meets Europe',
    description:
      "Everything you need for Tangier: the Kasbah, Cap Spartel, literary heritage, ferries to Spain, Al Boraq TGV, restaurants, day trips, and a complete guide to Morocco's gateway between continents.",
    url: 'https://moroccoguide.com/tangier',
    type: 'article',
    images: [
      {
        url: '/images/hero-tangier-bay.webp',
        width: 1200,
        height: 630,
        alt: 'Panoramic view of Tangier Bay with the medina and port at golden hour',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Tangier Travel Guide 2025-2026 | Where Africa Meets Europe',
    description:
      'Complete guide to Tangier: Kasbah, Cap Spartel, Caves of Hercules, Beat Generation trail, ferries to Spain, TGV train, restaurants, Cafe Hafa, day trips, and practical tips.',
    images: ['/images/hero-tangier-bay.webp'],
  },
  alternates: {
    canonical: 'https://moroccoguide.com/tangier',
  },
};
